/***
1.	INSERTION OPERATIONS
    a.	INSERT NODE AT BEGINNING OF THE LIST
    b.	INSERT NODE AT END OF THE LIST
    c.	INSERT NODE AFTER SPECIFIC NODE
    d.	INSERT NODE BEFORE SPECIFIC NODE

2.	DELETION OPERATIONS
    a.	DELETE NODE FROM BEGINNING OF THE LIST
    b.	DELETE NODE FROM END OF THE LIST
    c.	DELETE NODE AFTER SPECIFIC NODE
    d.	DELETE NODE BEFORE SPECIFIC NODE

***/
#include<iostream>
#include "DoublyLinkedList.h"

int main(){

return 0;
}
